# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e1dc48176ba23d91d9f387ccc4b6d2d3fc8e5f55da6a3f82052bfdb512a775ada1819e665b44f02cccfceaa5c167f2a895f1a45a07105ba4b1c3df882f2170

test:
  secret_key_base: 43ef0864daf370aedeced861a0d1423c5409b07417b1ef961204fcb70d52c350acb22938e1ea8ff2ce9b5920260416fb8f1a1a831dd4989b6c13aa9644c4dc9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
